### ISSUE TITLE
Cannot Enter Custom Numeric Pin

### ISSUE THREAD

**Issue by alldritt** [TimOliver/TOPasscodeViewController#10]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using? pulled Nov 11, 2017
Which version of iOS are you running? iOS 11
What model of iOS device were you testing on? iPhone 7, iPhone 8 (simulator)
If using CocoaPods, which version of CocoaPods are you on? 1.3.1

## Goals

I'm testing the library and I find that when I setup a custom numeric pin, the TOPasscodeViewController does not allow me to enter the pin code I've set.   The problem is there is no way to indicate the pin is complete.

## Expected Results

I would expect to be able to enter the pin code.

## Actual Results

TOPasscodeViewController keeps letting me enter digits and never ends.  The only way out is to delete the digits entered and cancel the panel.

## Steps to Reproduce

1. Run the TOPasscodeViewController example application.
2. Summon the settings panel
3. Set a new passcode by tapping on the Passcode row
4. Enter the original passcode (1234)
5. Tap the Passcode Options button
6. Tap "Custom Numeric Code"
7.  Enter a code ("123")
8. Tap Next
9. Reenter the code ("123")
10. Tap Done
11. Tap Done again to exit the Settings panel
12. Tap Enter Password
13. Enter the code ("123")

then what?

**Comment by TimOliver** [comment]
Sorry the delay @alldritt! 

I just spent a few hours tracking this down. It seems to be a bug I missed that only affected mid-size iPhones (iPhone 6, 7, 8 and X). I can't believe I missed it somehow.

It's fixed and live in v0.0.2 now.

Thanks for bringing this to my attention!

**Comment by alldritt** [comment]
No worries - thank you for resolving this.  And thank you for making TOPasscodeViewController available, it saved be a bunch of time.

**Comment by TimOliver** [comment]
Awesome! Glad to hear that!

My pleasure! I'm happy to hear you've found it useful!
