### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by zdog01** [TimOliver/TOPasscodeViewController#12]
I love this so much. Great work.
But all my apps are built in Swift, it would be great if It had a swift version as well.

Please and thanks :)

**Comment by TimOliver** [comment]
Thanks a lot @zdog01! Glad you like it?

Ummm, what do you mean by Swift support exactly? What trouble are you having with it exactly?

**Comment by TimOliver** [comment]
Gonna close this one off. :) I might give this one the same Swift wrapper treatment as `TOCropViewController` at some point, but this library will always be Objective-C. It took several months to write it, so it's not realistic to rewrite it in Swift anytime soon.

As long as you link it via a dynamic framework, you shouldn't have any Objective-C code interfering with your Swift apps. :)
