### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by LukA888** [TimOliver/TOPasscodeViewController#15]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using? 0.0.1
Which version of iOS are you running? iOS 11
What model of iOS device were you testing on? iPhone X
If using CocoaPods, which version of CocoaPods are you on? 1.3.1

## Goals

What is the outcome result you want to achieve with this library?

Provide the possibility to lock an app.

## Expected Results

What did you expect to happen?

A) Home indicator should respect safe area insets.
B) Touch ID replacement for Face ID.

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

![simulator screen shot - iphone x - 2017-12-14 at 13 10 51](https://user-images.githubusercontent.com/18327422/33992215-0389bf62-e0d2-11e7-8d59-116675ccc7a4.png)
![simulator screen shot - iphone x - 2017-12-14 at 13 11 09](https://user-images.githubusercontent.com/18327422/33992224-0e5d4a26-e0d2-11e7-80ad-a89359aeea14.png)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

A) Present a TOPasscodeSettingsViewController.
B) Present a TOPasscodeViewController with allowBiometricValidation = YES;

**Comment by TimOliver** [comment]
Thanks for filling out the issue template so thoroughly!

We already had a few contributions for iPhone X support, but there were still a few gaps. Thanks for the heads-up!

I just updated the `master` branch with provisions for both the keypad view, and for changing the biometrics button to say 'Face ID'. Because the passcode view controller itself isn't meant to have any internal code related to actual validation, 'Face ID' is exposed as a property on the main view controller class. :)

Let me know if that's all good for you! :)

**Comment by LukA888** [comment]
Thank you for your fast answer!

However, I couldn't test your changes because the library doesn't update. I'll try to explain myself.

I'm using cocoapods and I did the following things to try the changes:
- _gem install cocoapods_
- _pod repo update_ 
- _pod update TOPasscodeViewController_

In other hand, I've seen the changes in the example project and that's perfect 👏 👏

**Comment by TimOliver** [comment]
No worries! No I haven’t pushed it to CocoaPods yet. I need to fix some other stuff first.

For now, you should be able to point your Poddile directly at the master branch like this:

```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
```

**Comment by LukA888** [comment]
Ahhh, I see.

Thank you! 😄

**Comment by TimOliver** [comment]
The pod's been pushed as version 0.0.2 now. Let me know if you still have any problems with it. :)
