### ISSUE TITLE
Localization while using in swift

### ISSUE THREAD

**Issue by AwaisMobeen** [TimOliver/TOPasscodeViewController#37]
I am using this pod in a swift project and i am unable to localize according to the current locale of app. how could i do that

**Comment by TimOliver** [comment]
Hi @AwaisMobeen! I need more information before I can help. Please make sure to properly fill out the issue template next time.

What do you mean locale? Do you want to change the styling of the keypad text? At the moment, the library has no support for any localization, so they would need to be added from this point onwards.

**Comment by AwaisMobeen** [comment]
I am using this library in a swift project when I change the language of the application whole

**Comment by AwaisMobeen** [comment]
I have done making it a local library and adding a bridging header
