### ISSUE TITLE
Application rejected by Apple.

### ISSUE THREAD

**Issue by tapannathvani** [TimOliver/TOPasscodeViewController#39]
Apple rejected application because of same Lock screen design that confuse user.

So we are trying to apply titleView but its not working.

    self.pinAuthentication.passcodeView.titleView = {
                let i = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
                i.backgroundColor = .red
     //              //  let width = self.pinAuthentication.passcodeView.titleLabel.bounds.width
     //                let iview = UIImageView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
    //                iview.image = UIImage(named:"AppIcon")
    //                iview.contentMode = .scaleAspectFit
                return i
                }()

Can you please help us out to get out of this issue as we need to submit our App ASAP. We already use our custom title to create/enter/confirm PIN message

**Comment by TimOliver** [comment]
Closing this off in favour of keeping the conversation going in #31.
