### ISSUE TITLE
TOPasscodeKeypadView is inaccessible

### ISSUE THREAD

**Issue by ARGAMX** [TimOliver/TOPasscodeViewController#41]
Hello.

I have made **TOPasscodeViewController.framework** file from this project manually downloaded it.
After I have Included this framework in Swift project.
Made **import TOPasscodeViewController**.
All was perfect, even can chow **TOPasscodeViewController** on screen.
Seems all OK.

BUT.

When I started customization I found some limitations.
**TOPasscodeKeypadView** under **TOPasscodeView** is inaccessible.
Other simple props, like **titleLabel** is accecable.
But **keypadView** and **inputField** is not.

http://dl3.joxi.net/drive/2020/03/24/0014/1145/935033/33/2f38cbf5f1.jpg

http://dl3.joxi.net/drive/2020/03/24/0014/1145/935033/33/0950b88d93.jpg

Looks like not expected behavior, because it prevents from customization KeypadView.
Now I am try to make it public and accessible. (move it from **Private Headers** to **Headers**)

How I can access keypadView?

Thanks.

**Comment by ARGAMX** [comment]
I have resolved that problem and made PR:

https://github.com/TimOliver/TOPasscodeViewController/pull/43

**Comment by ARGAMX** [comment]
Also I am thinking about to make other private props available too.
Because that nice framework suffering from Apple Review I think it should provide more customizations properties.

**Comment by TimOliver** [comment]
Aha. Nice catch! Thanks for the PR!

Yes, it's a bit inconvenient that it has to be redesigned for that reason. Other users have reported that changing the circles to squares has worked in the past.

I plan to do a proper redesign soon. :)

**Comment by TimOliver** [comment]
Closed due to PR #43
